version: '2'

networks:
  gallifrey:
    external: true

volumes:
  database: {}
  backups: {}
  static: {}
  caddy: {}
  media: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - database:/var/lib/postgresql/data
      - backups:/backups
    env_file: .env
    networks:
      - gallifrey

  django-a:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    ports:
      - "5000"
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env
    networks:
      - gallifrey

  django-b:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    ports:
      - "5000"
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env
    networks:
      - gallifrey

  redis:
    build: ./compose/redis
    networks:
      - gallifrey
